-- MySQL Script generated by MySQL Workbench
-- Thu Nov  7 18:47:12 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sklep
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sklep
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sklep` DEFAULT CHARACTER SET utf8 ;
USE `sklep` ;

-- -----------------------------------------------------
-- Table `sklep`.`adres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sklep`.`adres` (
  `id_adres` INT NOT NULL AUTO_INCREMENT,
  `wojewodztwo` VARCHAR(45) NOT NULL,
  `kod_pocztowy` VARCHAR(6) NOT NULL,
  `miasto` VARCHAR(45) NOT NULL,
  `ulica` VARCHAR(45) NOT NULL,
  `nr_domu` INT NOT NULL,
  `nr_lokalu` INT NULL,
  PRIMARY KEY (`id_adres`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sklep`.`klienci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sklep`.`klienci` (
  `id_klienci` INT NOT NULL AUTO_INCREMENT,
  `Imie` VARCHAR(45) NOT NULL,
  `Nazwisko` VARCHAR(45) NOT NULL,
  `haslo(md5)` VARCHAR(45) NOT NULL,
  `e-mail` VARCHAR(45) NOT NULL,
  `id_adres` INT NOT NULL,
  PRIMARY KEY (`id_klienci`),
  INDEX `fk_klienci_adres_idx` (`id_adres` ASC),
  CONSTRAINT `fk_klienci_adres`
    FOREIGN KEY (`id_adres`)
    REFERENCES `mydb`.`adres` (`id_adres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sklep`.`kategorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sklep`.`kategorie` (
  `id_kategorie` INT NOT NULL AUTO_INCREMENT,
  `kategoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_kategorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sklep`.`produkty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sklep`.`produkty` (
  `id_produkty` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(45) NOT NULL,
  `opis` TEXT NOT NULL,
  `opinie_klientow` TEXT NULL,
  `cena` DECIMAL(10,2) NOT NULL,
  `dostepna_ilosc` INT NOT NULL,
  `producent` VARCHAR(45) NOT NULL,
  `oceny` ENUM('1', '2', '3', '4', '5') NULL,
  `rozmiar` VARCHAR(5) NOT NULL,
  `id_kategorie` INT NOT NULL,
  `id_klienci` INT NULL,
  PRIMARY KEY (`id_produkty`),
  INDEX `fk_produkty_kategorie1_idx` (`id_kategorie` ASC),
  INDEX `fk_produkty_klienci1_idx` (`id_klienci` ASC),
  CONSTRAINT `fk_produkty_kategorie1`
    FOREIGN KEY (`id_kategorie`)
    REFERENCES `mydb`.`kategorie` (`id_kategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produkty_klienci1`
    FOREIGN KEY (`id_klienci`)
    REFERENCES `mydb`.`klienci` (`id_klienci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sklep`.`zamowienie_produkty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sklep`.`zamowienie_produkty` (
  `id_zamowienie_produkty` INT NOT NULL AUTO_INCREMENT,
  `ile_sztuk` INT NOT NULL,
  `id_produkty` INT NOT NULL,
  PRIMARY KEY (`id_zamowienie_produkty`),
  INDEX `fk_zamowienie_produkty_produkty1_idx` (`id_produkty` ASC),
  CONSTRAINT `fk_zamowienie_produkty_produkty1`
    FOREIGN KEY (`id_produkty`)
    REFERENCES `mydb`.`produkty` (`id_produkty`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sklep`.`zamowienia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sklep`.`zamowienia` (
  `id_zamowienia` INT NOT NULL AUTO_INCREMENT,
  `data_zlozenia` DATETIME NOT NULL,
  `data_wyslania` DATETIME NOT NULL,
  `zaplacono` TINYINT NOT NULL,
  `id_klienci` INT NOT NULL,
  `id_zamowienie_produkty` INT NOT NULL,
  PRIMARY KEY (`id_zamowienia`),
  INDEX `fk_zamowienia_klienci1_idx` (`id_klienci` ASC),
  INDEX `fk_zamowienia_zamowienie_produkty1_idx` (`id_zamowienie_produkty` ASC),
  CONSTRAINT `fk_zamowienia_klienci1`
    FOREIGN KEY (`id_klienci`)
    REFERENCES `mydb`.`klienci` (`id_klienci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zamowienia_zamowienie_produkty1`
    FOREIGN KEY (`id_zamowienie_produkty`)
    REFERENCES `mydb`.`zamowienie_produkty` (`id_zamowienie_produkty`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sklep`.`oferta_dnia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sklep`.`oferta_dnia` (
  `id_oferta_dnia` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `cena_w_dniu` DECIMAL(10,2) NOT NULL,
  `id_produkty` INT NOT NULL,
  PRIMARY KEY (`id_oferta_dnia`),
  INDEX `fk_oferta_dnia_produkty1_idx` (`id_produkty` ASC),
  CONSTRAINT `fk_oferta_dnia_produkty1`
    FOREIGN KEY (`id_produkty`)
    REFERENCES `mydb`.`produkty` (`id_produkty`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sklep`.`promocje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sklep`.`promocje` (
  `id_promocje` INT NOT NULL AUTO_INCREMENT,
  `nowa_cena` DECIMAL(10,2) NOT NULL,
  `id_produkty` INT NOT NULL,
  PRIMARY KEY (`id_promocje`),
  INDEX `fk_promocje_produkty1_idx` (`id_produkty` ASC),
  CONSTRAINT `fk_promocje_produkty1`
    FOREIGN KEY (`id_produkty`)
    REFERENCES `mydb`.`produkty` (`id_produkty`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
